### ISSUE TITLE
Revidere løsningsforslag

### ISSUE THREAD

**Issue by leogasnier** [Altinn/altinn-broker#103]
FRIST 8/9 
I forbindelse med KS2 må løsningsforslagene våre revideres

Sjekkliste: https://digdir.sharepoint.com/:p:/r/sites/Prosjekt_NyeAltinn/Delte%20dokumenter/0.%20Administrasjon/Produkteierm%C3%B8ter/Sjekkliste_PE_Github_KS2.pptx?d=w3dc72714eeef48c482e69a3e55ed1577&csf=1&web=1&e=a8uYiv

Tydeliggjøre tekniske krav - veikart - milepæler detaljeres - estimering/budsjettrevisjon
```[tasklist]
### Tasks
- [x] estimering på milestones
- [x] kravtabell
- [x] alle tags i styringsdok
- [x] usikkerhet
```

```[tasklist]
### Tasks
- [x] oppdatere veikart i løsningsbeskrivelse
- [x] avklare "merkantilt" - må fjernes eller oppdateres.
```

**Comment by leogasnier** [comment]
ønskes levert medio sept.

**Comment by leogasnier** [comment]
https://digdir.sharepoint.com/sites/Prosjekt_NyeAltinn/Delte%20dokumenter/Forms/AllItems.aspx?csf=1&web=1&e=gn8As4&OR=Teams%2DHL&CT=1693903684063&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyOC8yMzA3MDMwNzM0NiIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D&cid=68394dea%2D6918%2D4fef%2D9a0e%2D9aeb90883007&RootFolder=%2Fsites%2FProsjekt%5FNyeAltinn%2FDelte%20dokumenter%2F7%2E%20KS2%2FKS2%2Ddokumenter%2F1%2E%20Styringsdokumenter%2FStyringsdokument%20Digdir%2FVedlegg%5Fl%C3%B8sningsforslag&FolderCTID=0x0120003FEB0EF225430A49B033233E76DA42A9
