### ISSUE TITLE
Etablere infrastruktur for bygg, deploy og test

### ISSUE THREAD

**Issue by RagnarFatland-Avanade** [Altinn/altinn-broker#105]
### Title, User role(s), and Users value statement(s)

Title: Etablere infrastruktur for bygg, deploy og test
User role(s): Provider, Developer
Users value statement(s):
TBD

### Description

**High level features (capabilities):**
Infrastruktur som støtter automatisert bygg, deploy, Continuous Integration og test.

**Additional information:**

- Må utføres på en måte som legger til rette for god kodekvalitet og muliggjør hyppige releaser.
- Tilrettelegge for eksterne bidrag.

```[tasklist]
### Features
- [x] Oppsett for Pull Requests som sikrer gode kode-reviews
- [x] Code analysis ved build for å sikre kode kvalitet
- [ ] https://github.com/Altinn/altinn-broker/issues/108
- [x] Automatisk bygg/deploy på utviklingsimage
- [ ] https://github.com/Altinn/altinn-broker/issues/149
- [ ] https://github.com/Altinn/altinn-broker/issues/150
- [ ] https://github.com/Altinn/altinn-broker/issues/138
```

```[tasklist]
### Work Items
```
