### ISSUE TITLE
Analyse - api som understøtter migrering

### ISSUE THREAD

**Issue by leogasnier** [Altinn/altinn-broker#134]
Realistisk tilnærming til hvordan trafikk kan flyttes fra Altinn 2 api - til altinn 3, for å understøtte migrering av tjenestene.

Utkast bør presenteres i åpent møte 11.10

Spesifikasjon bør adressere alle funksjoner som er i bruk i Altinn 2, og endringer fra dagens api/konsekvenser for brukere må beskrives. Eks. overgang til autentisering med maskinporten, RRR osv.
```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-broker/issues/137
- [ ] https://github.com/Altinn/altinn-broker/issues/131
- [ ] https://github.com/Altinn/altinn-broker/issues/175
```

**Comment by RagnarFatland-Avanade** [comment]
Jeg har gjort noe avklaringer og diskusjoner med @tomshag, @Ceredron og litt med @erikhag1 , her er skissert hvilke alternativer.
Jeg foreslår at vi kan ta et møte og diskutere dette videre i uke 41, evt. uke 42 når @leogasnier er tilbake.
![image](https://github.com/Altinn/altinn-broker/assets/99019701/73754797-4fe6-40f3-b8da-8cecfdb6a375)

**Comment by RagnarFatland-Avanade** [comment]
Jeg kjører et møte tirsdag 17.10 med noen av Auth* folkene der vi forsøker avklare litt rundt problematikken av autentisering på tvers.

**Comment by erikhag1** [comment]
Se ellers presentasjon fra åpent møte under https://digdir.sharepoint.com/sites/PGMeldingsutveksling/Delte%20dokumenter/Forms/AllItems.aspx?RootFolder=%2Fsites%2FPGMeldingsutveksling%2FDelte%20dokumenter%2FGeneral%2FAltinn%20migrering%2FFormidling%2F%C3%85pne%20m%C3%B8ter&FolderCTID=0x012000FD775BBF6545D24089FF35840CE048C0, med noen slides som illustrerer alternative og sier litt om autentisering og autorisering i Altinn2 og Altinn3.

**Comment by leogasnier** [comment]
Inviter meg til et møte for gjennomgang og beslutning før denne lukkes.

**Comment by RagnarFatland-Avanade** [comment]
Siste skisse, vi går gjennom dette i møtet 25.10:
![image](https://github.com/Altinn/altinn-broker/assets/99019701/25c2165d-6491-406d-8859-e6624ad5465b)

**Comment by RagnarFatland-Avanade** [comment]
Alternativ A: Uavhengige løsninger
	- Altinn 2-løsningen og Altinn 3-løsningene kjører helt uavhengig av hverandre.
	- Man migrerer enkelt-formidlingstjenester til ny løsning kontrollert etter avtale med alle integratører som benytter gitt tjeneste.

Anbefaling: Dette alternativet er ikke aktuelt da vi ser for at det gjør migrering lite smidig og vil føre til at det tar lang tid før A3-løsning når kritisk masse.

Alternativ B:
Det gjøres en sammenkobling av Altinn 2 og Altinn 3 slik at forsendelser kan gå på tvers:
	- Nye Løsning bygges med nok fellestrekk i prosessen til at man kan kjøre en forsendelse via enten A2 eller A3.
	- Uansett hvilken plattform man benytter, så kan man utveksle data med hverandre
	- Gjør det lettere å migrere enkelte brukere til ny løsning, uten at man må koordinere alle på en gang.
	- Mulighet for konsumentene å relativt sømløst skifte mellom ny/gammel løsning.
	- Dette gjøres kun for de formidlingstjenester der det er nødvendig; disse kalles "synkroniserte formidlingstjenester";
		- Det gjøres en kobling mellom en gitt A2 Formidlingstjeneste og en gitt A3 Formidlingstjeneste i konfigurasjon.
			§ A3 RessursRegister har denne mulig fra før.
			§ En enkel config-liste i A2 Config kan løse det på den siden.
		- Restriksjoner på A3-versjon slik at de holdes kompatible;
			§ Maks størrelse 1GB.
			§ Kun 1 fil per forsendelse.
	- Krever nye API-endepunkter som omgår vanlig autorisasjonsmodell slik at man kan kalle på tvers.
		- Tilsvarende som SBLBridge, men at man også kan gå fra A2 til A3, i tillegg til bare fra A3 til A2.
			§ IP-filtrert Expressroute mellom On-Prem og Cloud
			§ Basic autentisering eller en annnen Shared secret for autentisering mot "bridge"-API.

Det er 3 hovedmåter dette kan gjennomføres:

Alternativ "B1" Begge løsninger i parallell, men synkronisering på tvers
	- Det skjer en synkronisering i bakkant mellom A2 og A3 slik at filer/forsendelser tilgjengeliggjøres på tvers.
		- En batch-jobb som kaller spesialiserte API for å synkronisere på tvers.

Pros:
	- Ved nedetid i synkroniseringen så vil fremdeles hver løsning fungere selv om kommunikasjonen på tvers ikke vil fungere. Når synkroniseringen blir gjenopptatt bør man relativt raskt kunne få harmoni på tvers.
	- Siden konsumentenes kall alltid skjer mot kun 1 plattform, vil de ikke oppleve tregheter i sine metodekall siden disse ikke går på tvers.
	- Logikken i Altinn 2 tjenestekoden forblir uberørt.

Cons:
	- Duplisering av data / databaseinnslag.
	- Juridiske utfordringer ift. Timestamps.
	- Krever en utvikling av en Batch-komponent som kjører ofte for å synkronisere på tvers.
	- Det må forventes noe tidsforsinkelser når det skal synkroniseres på tvers av løsningene, spesielt dersom synk-jobben er treg eller kjører sjelden.
	
Alternativ "B2" Begge løsninger i parallell, og det gjøres kall i bakkant til en gitt formidlingstjenestes "hjemsted"
	- De synkroniserte Formidlingstjenestene har et "hjemsted" som er løsningen der den hører hjemme som må være konfigurerbart i fil eller database og skal kunne endres ved planlagte overganger.
	- Når en konsument vil ha tilgang til en fil i en annen versjon, fungerer i praksis løsningene som skall til hverandre
		- Det gjøres en sjekk på om tjenesten har "hjemsted" i annen løsning, og hvis tilfelle så kalles API for aktuell løsning.
		- Autentisering og autorisasjon gjøres i hver respektive løsning før kallet eventuelt rutes over.
Pros:
	- Mulighet for konsumentene å relativt sømløst skifte mellom ny/gammel løsning.
	- Unngår duplisering av data / databaseinnslag.
	
Cons:
	- Krever fremdeles at man på et gitt tidspunkt endrer tjenesten til å ha hjemsted i Altinn 3
	- Endringer av A2 tjenestekode for å støtte kall til A3-lag og kan introdusere ustabilitet i eksisterende løsning.
	- Det må forventes noe tidsforsinkelser når det kommuniseres på tvers av løsningene.
	- Ved nedetid i kommunikasjonen på tvers av plattformene så vil alle tjenestekall som "krysser grensen" feile.
	- Krever fremdeles noe koordinering når tjenesten skal migreres til Altinn 3.

Alternativ "B3" Begge løsninger i parallell, og det gjøres kall i bakkant til en gitt forsendelses "hjemsted"
	- De synkroniserte Formidlingstjenestene har et "hjemsted" per forsendelse som er løsningen der alle data og filer lagres.
	- Hjemstedet til en forsendelse settes som konsekvens av at avsender gjør initialisering og opplastning mot sin valgte plattform.
	- Når en konsument vil ha tilgang til en forsendelse i annen løsning, fungerer i praksis løsningene som skall til hverandre.
		- Det gjøres en sjekk på om tjenesten er synkronisert, og avhengig av tilfellet, så kalles API for annen løsning. 
Pros:
	- Mulighet for konsumentene å sømløst skifte mellom ny/gammel løsning siden hver enkelt forsendelse vil høre hjemme i én løsning.
	- Krever ikke endring av Tjenestens hjemsted når man skal skru av Altinn 2, kun en oppdatering i Altinn 3-konfig for å stanse kallene på tvers.
	- Unngår duplisering av data / databaseinnslag.
	
Cons:
	• Endringer av A2 tjenestekode for å støtte kall til A3-lag og kan introdusere ustabilitet i eksisterende løsning.
	• Det må forventes noe tidsforsinkelser når det kommuniseres på tvers av løsningene.
	• Ved nedetid i kommunikasjonen på tvers av plattformene så vil alle tjenestekall som "krysser grensen" feile.
	• Det blir noe kompleksitet ved "GetShipment/CheckIfAvailableShipment" da man må alltid gjøre kall på tvers for synkroniserte tjenester.

Vurdering av B-alternativene:
Dette vil gjøre det mulig for en miks av brukere på både gammel og ny versjon av tjenesten, noe som kan gjøre det lettere å planlegge migrering siden man ikke må ta "hard switch" som i Alternativ A.
Setter fremdeles et press på at alle brukere må over på A3 løsningen innen A2-Shutdown, men det blir mulig å gjøre dette mer gradvis siden man kommuniserer på tvers.

Det må gjøres en vurdering på hva som smerter mest:
	• Dataduplisering
	• Respons/prosesseringstid
	• Risiko for ustabilitet

Av disse ser B3 per nå ut som mest aktuell løsning.
Diskusjon i møte 25.10:
	- B1 bør ut pga Dataduplisering
	

Alternativ C - Fasade-løsninger.

Alternativ "C1" - Hel fasade-løsning i Altinn 2
	- Endepunkt i Altinn 2 blir endret til å være en Fasade over Altinn 3-implementasjonen.
	- Krever som Alt B at ny prosess i stor grad kan kjøres på samme måte som gammel.
	- Altinn 2 API'ene reduseres til fasader/skall som kun kaller videre til Altinn 3 API.

Pros:
	- Man må ikke lenger vedlikeholde Altinn 2-kodebasen og datalager
	- Eksisterende brukere kan i større grad utnytte de nye mulighetene som A3 bringer, uten å måtte integrere seg mot nye A3-endepunkt.
	
Cons:
	- Autentisering/Autorisasjon vil være utfordring; man må nok fremdeles benytte A2 sin stack videre, spesielt for de systembrukere og autentiseringsmetodene som ikke støttes i A3, som Basic og EC2.
	- A2 brukere kan merke en endring i bruksmønsteret som følge av at A3 benyttes som basis.

Alternativ "C2" - Hel fasade-løsning i Altinn 3
	- Endepunkt i Altinn 3 blir endret til å være en Fasade over Altinn 2-implementasjonen.
	- Krever som Alt B at ny prosess i stor grad kan kjøres på samme måte som gammel.
	- Altinn 3 API'ene reduseres til fasader/skall som kun kaller videre til Altinn 2 API inntil man får implementert funksjonalitet på Altinn 3.

Pros:
	- Uansett hvilken versjon av formidlingstjenesten av man benytter, så kan man utveksle data med hverandre
	- Gjør det lettere å migrere enkelte brukere til ny løsning, uten at man må koordinere alle på en gang.
	- Man kommer raskere i gang med å publisere Altinn 3-endepunktene.

Cons:
	- Man må fremdeles forholde seg til de tekniske begrensingene i Altinn 2 plattform
	- Altinn 3 Autorisasjonskomponenter, spesielt ny SystemBruker og Ressurs Rettighets Register er ikke klare ennå, noe som gjør at endepunktene i så fall må tilgjengeliggjøres uten autorisasjon.

Vurdering av C-alternativ:
At det tar tid å få autorisasjon/RRR på plass på i A3 gjør at det er begrenset nytte å gjøre A3-løsningen til en fasade over A2 da dette først vil være mulig et stykke ut i utviklingen av A3-versjonen, noe som gjør at A3-komponentene kan være modne nok til å tas fullt i bruk.
Av disse to er derfor C1 bedre enn C2, men er først aktuell når A3-versjonen er noe mer moden og utprøvd.

Alternativ D: "Emulert Altinn 2"-løsning.
	- C1 tatt helt ut av Altinn 2 stacken og hostet i skyen.
	- Aktuelt kun ved EOL Altinn 2 platform.
Cons:
	- Bygge/emulere egen Auth*-løsning

Total anbefaling;
B3 eller B2 gitt at man ikke er redd for å tukle med A2-tjenestekoden og at man får optimalisert logikk/trafikk på tvers.
Dersom man ser fremdeles at man har brukere på Altinn 2 ved Atlinn 2 End-of-Life, kan man bruke dette som basis for løsning D.

**Comment by RagnarFatland-Avanade** [comment]
Oppdatert beskrivelse per 09.11.2023.
Gamle kommentarer ryddes vekk for lesbarhets skyld.

**Alternativ A: Uavhengige løsninger**
	- Altinn 2-løsningen og Altinn 3-løsningene kjører helt uavhengig av hverandre.
	- Man migrerer enkelt-formidlingstjenester til ny løsning kontrollert etter avtale med alle integratører som benytter gitt tjeneste.

**Anbefaling**: Dette alternativet er ikke aktuelt da vi ser for at det gjør migrering lite smidig og vil føre til at det tar lang tid før A3-løsning når kritisk masse.

**Alternativ B: Løsninger i parallell, med sammenkobling**
Det gjøres en sammenkobling av Altinn 2 og Altinn 3 slik at forsendelser kan gå på tvers:
- Nye løsning bygges med nok fellestrekk i prosessen til at man kan kjøre en forsendelse via enten A2 eller A3.
- Uansett hvilken plattform man benytter, så kan man utveksle data med hverandre
- Gjør det lettere å migrere enkelte brukere til ny løsning, uten at man må koordinere alle på en gang.
- Mulighet for konsumentene å relativt sømløst skifte mellom ny/gammel løsning.
- Dette gjøres kun for de formidlingstjenester der det er nødvendig; disse kalles "synkroniserte formidlingstjenester";
- Det gjøres en kobling mellom en gitt A2 Formidlingstjeneste og en gitt A3 Formidlingstjeneste i konfigurasjon.
  - A3 RessursRegister har denne mulig fra før.
    - En enkel config-liste i A2 Config kan løse det på den siden.
  - Restriksjoner på A3-versjon slik at de holdes kompatible;
     - Maks størrelse 1GB.
     - Kun 1 fil per forsendelse.
- Krever nye API-endepunkter som omgår vanlig autorisasjonsmodell slik at man kan kalle på tvers.
  - Tilsvarende som SBLBridge, men at man også kan gå fra A2 til A3, i tillegg til bare fra A3 til A2.
   - IP-filtrert Expressroute mellom On-Prem og Cloud
   - Basic autentisering eller en annen Shared secret for autentisering mot "bridge"-API.

Det er 3 hovedmåter dette kan gjennomføres:
Alternativ "B1" Begge løsninger i parallell, men synkronisering på tvers
- Det skjer en synkronisering i bakkant mellom A2 og A3 slik at filer/forsendelser tilgjengeliggjøres på tvers.
- En batch-jobb som kaller spesialiserte API for å synkronisere på tvers.

Pros:
- Logikken i Altinn 2 tjenestekoden forblir uberørt.
- Ved nedetid i synkroniseringen så vil fremdeles hver løsning fungere selv om kommunikasjonen på tvers ikke vil fungere. Når synkroniseringen blir gjenopptatt bør man relativt raskt kunne få harmoni på tvers.
- Siden konsumentenes kall alltid skjer mot kun 1 plattform, vil de ikke oppleve tregheter i sine metodekall siden disse ikke går på tvers.

Cons:
- Duplisering av data / databaseinnslag.
- Juridiske utfordringer ift. Timestamps.
- Krever en utvikling av en Batch-komponent som kjører ofte for å synkronisere på tvers.
- Det må forventes noe tidsforsinkelser når det synkroniseres på tvers av løsningene, spesielt dersom synk-jobben er treg eller kjører sjelden.
	
**Alternativ "B2":** Begge løsninger i parallell, og det gjøres kall i bakkant til en gitt formidlingstjenestes "hjemsted"
- De synkroniserte Formidlingstjenestene har et "hjemsted" som er løsningen der den hører hjemme som må være konfigurerbart i fil eller database og skal kunne endres ved planlagte overganger.
  - Når en konsument vil ha tilgang til en fil i en annen versjon, fungerer i praksis løsningene som skall til hverandre
   - Det gjøres en sjekk på om tjenesten har "hjemsted" i annen løsning, og hvis tilfelle så kalles API for aktuell løsning.
- Autentisering og autorisasjon gjøres i hver respektive løsning før kallet eventuelt rutes over.

Pros:
- Mulighet for konsumentene å relativt sømløst skifte mellom ny/gammel løsning.
- Unngår duplisering av data / databaseinnslag.
	
Cons:
- Krever fremdeles at man på et gitt tidspunkt endrer tjenesten til å ha hjemsted i Altinn 3 og at dette må koordineres, og eventuelle data migreres.
- Det blir endringer av A2 tjenestekode for å støtte kall til A3-lag og kan introdusere ustabilitet i eksisterende løsning.
- Det må forventes noe tidsforsinkelser når det kommuniseres på tvers av løsningene.
- Ved nedetid i kommunikasjonen på tvers av plattformene så vil alle tjenestekall som "krysser grensen" feile, noe som må håndteres på en god måte.

**Alternativ "B3":** Begge løsninger i parallell, og det gjøres kall i bakkant til en gitt forsendelses "hjemsted"
- De synkroniserte Formidlingstjenestene har et "hjemsted" per forsendelse som er løsningen der alle data og filer lagres.
- Hjemstedet til en forsendelse settes som konsekvens av at avsender gjør initialisering og opplastning mot sin valgte plattform.
- Når en konsument vil ha tilgang til en forsendelse i annen løsning, fungerer i praksis løsningene som skall til hverandre.
  - Det gjøres en sjekk på om tjenesten er synkronisert, og avhengig av tilfellet, så kalles API for annen løsning. 

Pros:
- Mulighet for konsumentene å sømløst skifte mellom ny/gammel løsning siden hver enkelt forsendelse vil høre hjemme i én løsning.
- Krever ikke endring av Tjenestens hjemsted når man skal skru av Altinn 2, kun en oppdatering i Altinn 3-konfig for å stanse kallene på tvers.
- Unngår duplisering av data / databaseinnslag.
	
Cons:
- Endringer av A2 tjenestekode for å støtte kall til A3-lag og kan introdusere ustabilitet i eksisterende løsning.
- Det må forventes noe tidsforsinkelser når det kommuniseres på tvers av løsningene.
- Ved nedetid i kommunikasjonen på tvers av plattformene så vil alle tjenestekall som "krysser grensen" feile.
- Det blir noe kompleksitet ved "GetShipment/CheckIfAvailableShipment" da man må alltid gjøre kall på tvers for synkroniserte tjenester.

**Vurdering av B-alternativene:**
Dette vil gjøre det mulig for en miks av brukere på både gammel og ny versjon av tjenesten, noe som kan gjøre det lettere å planlegge migrering siden man ikke må ta "hard switch" som i Alternativ A.
Setter fremdeles et press på at alle brukere må over på A3 løsningen innen A2-Shutdown, men det blir mulig å gjøre dette mer gradvis siden man kommuniserer på tvers.

Det må gjøres en endelig vurdering på hva som smerter mest:
- Dataduplisering
- Respons/prosesseringstid
- Risiko for ustabilitet

Av disse ser B3 per nå ut som mest aktuell løsning, B1 er minst aktuell på grunn av dataduplisering og timestamp-problematikk.

**Alternativ C - Fasade-løsninger.**

**Alternativ "C1":** Hel fasade-løsning i Altinn 2
- Endepunkt i Altinn 2 blir endret til å være en Fasade over Altinn 3-implementasjonen.
- Krever som Alt B at ny prosess i stor grad kan kjøres på samme måte som gammel.
- Altinn 2 API'ene reduseres til fasader/skall som kun kaller videre til Altinn 3 API.

Pros:
- Man må ikke lengre vedlikeholde Altinn 2-kodebasen og datalager
- Eksisterende brukere kan i større grad utnytte de nye mulighetene som A3 bringer, uten å måtte integrere seg mot nye A3-endepunkt.
	
Cons:
- Autentisering/Autorisasjon vil være utfordring; man må fremdeles benytte A2 sin stack videre, spesielt for de systembrukere og autentiserings metodene som ikke støttes i A3, som Basic og EC2.
- A2 brukere kan merke en endring i bruksmønsteret som følge av at A3 benyttes som basis.

**Alternativ "C2":** - Hel fasadeløsning i Altinn 3
- Endepunkt i Altinn 3 blir endret til å være en Fasade over Altinn 2-implementasjonen.
- Krever som Alt B at ny prosess i stor grad kan kjøres på samme måte som gammel.
- Altinn 3 API'ene reduseres til fasader/skall som kun kaller videre til Altinn 2 API inntil man får implementert funksjonalitet på Altinn 3.

Pros:
- Uansett hvilken versjon av formidlingstjenesten av man benytter, så kan man utveksle data med hverandre
- Gjør det lettere å migrere enkelte brukere til ny løsning, uten at man må koordinere alle på en gang.
- Man kommer raskere i gang med å publisere Altinn 3-endepunktene.

Cons:
- Man må fremdeles forholde seg til de tekniske begrensingene i Altinn 2 plattform
- Altinn 3 Autorisasjonskomponenter, spesielt ny SystemBruker og Ressurs Rettighets Register er ikke klare ennå, noe som gjør at endepunktene i så fall må tilgjengeliggjøres uten autorisasjon.

**Vurdering av C-alternativ:**
At det tar tid å få autorisasjon/RRR på plass på i A3 gjør at det er begrenset nytte å gjøre A3-løsningen til en fasade over A2 da dette først vil være mulig et stykke ut i utviklingen av A3-versjonen, noe som gjør at A3-komponentene kan være modne nok til å tas fullt i bruk.
Av disse to er derfor C1 bedre enn C2, men er først aktuell når A3-versjonen er noe mer moden og utprøvd.

**Alternativ D:** "Emulert Altinn 2"-løsning.
- C1 tatt helt ut av Altinn 2 stacken og hostet i skyen.
- Aktuelt kun ved EOL Altinn 2 platform.

Cons:
- Bygge/emulere egen Auth*-løsning

Total anbefaling;
B3 eller B2 gitt at man ikke er redd for å tukle med A2-tjenestekoden og at man får optimalisert logikk/trafikk på tvers.
Dersom man ser fremdeles at man har brukere på Altinn 2 ved Atlinn 2 End-of-Life, kan man bruke dette som basis for løsning D.

**Comment by RagnarFatland-Avanade** [comment]
Utførte møte i dag 16.11.2023, referat er under kvalitetssikring.
TLDR; en ny variant E ble foreslått. som er forenkling av B2 / C1, der tjenester i A3 tilgjengeliggjøres i A2.

**Comment by leogasnier** [comment]
@RagnarFatland-Avanade - er Alt. E og konsekvenser/endringer beskrevet noe sted?

**Comment by RagnarFatland-Avanade** [comment]
@leogasnier en foreløpig beskrivelse ligger i møtereferatet, vi kan ta en gjennomgang på kommende torsdag, se innkalling.

**Comment by leogasnier** [comment]
Veldig bra! Fokuser på å beskrive alt E/B4.. A kommer nok ikke på tale (Eks. Kartverket og BITS har ikke kontroll på bankene og meglere og deres systemleverandører, som visma), og jeg mener argumentene for E lett trumfer de andre alternativene. Når det er sagt så mener jeg vi skal få dagens tjenesteeiere til å sammen med oss sette en sluttdato for A2-apiene, i god tid før juni 2026.

**Comment by RagnarFatland-Avanade** [comment]
Oppdaterte overordnet overskrift med B4 og anbefalinger etter møtet 23.11.
Legger konklusjonen her:
Konklusjon:
- Alle som kan gå for Alternativ A anbefales dette.
- B4 peker seg ut som den aktuelle overgangsløsningen.
  - Kan også være basis for B2 dersom man senere blir tvunget til å implementere det.
- B2 kun dersom det blir sterkt press med bidrag/finansiering.
B4 blir den versjonen som dokumenteres og kommuniseres ut fremover.
