### ISSUE TITLE
Infrastructure-as-code for løsningen

### ISSUE THREAD

**Issue by Ceredron** [Altinn/altinn-broker#138]
### Description

Som utvikler ønsker jeg at hele infrastrukturen som kjører i skyen, dvs container/database/etc, kan spinnes opp fra bunnen av helt uten manuelle prosesser. Det sikrer mot uhell forårsaket av den menneskelige faktoren og gir oss et versjonskontrollert bilde av skyressursene våre.

### Additional Information

Azure Container Apps blir brukt mye av organisasjonen ellers. Databasen må være Postgres.

```[tasklist]
### Tasks
- [x] Arkitekturskisse
- [x] Click-ops prototyp
- [ ] https://github.com/Altinn/altinn-broker/issues/144
- [ ] Bakt inn i CI/CD pipeline
- [ ] https://github.com/Altinn/altinn-broker/issues/141
```
