### ISSUE TITLE
Logging and monitoring

### ISSUE THREAD

**Issue by Ceredron** [Altinn/altinn-broker#202]
### Title, User role(s), and Users value statement(s)

The user would like to be able to contact support and get troubleshooting for a failed operation.

### Description

A vendor would like to be be confident that problems are detected and handled on our end.

Noen stikkord rundt hva vår logging bør understøtte: 
- grunnlag for kostnadskontroll og oversikt
- Juridisk logg - revisjonslogg som viser hva som er gjort, av hvem og når, til bruk som bevis ol. (dette oppnås i kombinasjon med autorisasjons og autentiseringslogger)
- For teamet - innfri både tekniske og forretningsmessige behov for oversikt og kontroll på produktets tilstand til enhver tid
- Logging på tvers?! 1. dialogporten, 2 eFormidling?

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-broker/issues/186
- [ ] https://github.com/Altinn/altinn-broker/issues/205
- [ ] https://github.com/Altinn/altinn-broker/issues/80
```

**Comment by leogasnier** [comment]
minimum tilsvarende A2 - 
- Data som ligger til grunn for Aktivitetslogg, statusapi/events, statistikk/fakturaunderlag.
- Logger vi har teknisk behov for

OBS: kartverket/bits abbonerer på en spesialstatstikk for digital eiendomshandel.
