### ISSUE TITLE
Målformulering formidlingstjenesten basert på kjente brukerbehov og rammevilkår

### ISSUE THREAD

**Issue by leogasnier** [Altinn/altinn-broker#21]
Ting å vurdere:
Store filer/volum
sikkerhet/sporbarhet
maskin til maskin
fleksibilitet

Bør baseres på overordnede målsetninger, det vi vet om PG strategi, kjente behov osv. 

Som team trenger vi felles mål å jobbe mot, for å kunne prioritere riktig, og levere konsept, planlegging og MVP på tid og kost.
```[tasklist]
### Tasks
- [x] Mål og visjon
- [ ] https://github.com/Altinn/altinn-broker/issues/49
- [ ] https://github.com/Altinn/altinn-broker/issues/50
```

**Comment by leogasnier** [comment]
Kan ta utgangspunkt i denne: https://github.com/digdir/portfolio/issues/48
Og denne: https://digdir.sharepoint.com/:w:/s/Prosjekt_NyeAltinn/EQXo9Fd9HZZNkFVQOc0LVD8BERluu_HUPbeOPkjbJerSlg?e=yoU3fP

**Comment by leogasnier** [comment]
https://miro.com/app/board/uXjVMBuzPKw=/ - work in progress her.
