### ISSUE TITLE
Etablere IP-filtering mellom Altinn 2 og 3 for overgangsløsning

### ISSUE THREAD

**Issue by RagnarFatland** [Altinn/altinn-broker#249]
For å bidra til bedre sikkerhet og stabilitet for overgangsløsning så er det foreslått at vi benytter IP-filtering i APIM eller lignende for å isolere trafikken mellom Altinn 2 og endepunktet for overgangsløsningen som hostes i Altinn 3.

Å sette opp endepunktet i APIM vil eksponere det delvis selv om vi også der kan begrense tilgang.

Dette blir i stor grad en koordineringsjobb mot aktuelle personer i Infra-teament, som Espen Herskedal og Orange.

```[tasklist]
### Tasks
- [x] Sette opp Konfigurasjon i APIM for Leagacy-endepunkt, med IP-filtrering for Altinn 2 sin eksterne IP
- [ ] Eventuelle Brannmuråpninger mellom Altinn 2 APP-servere og Altinn 3 Broker endepunkt
- [ ] Eventuelle konfigurasjonsendringer i Altinn 2 BrokerLegacy url config.
```

**Comment by RagnarFatland-Avanade** [comment]
Altinn 2 sine eksterne IP'er for utgående trafikk er:
PROD; 89.250.123.17 
TT02; 89.250.123.58

**Comment by Ceredron** [comment]
Avventer overgangsløsning i APIM.

**Comment by Viktorolsen** [comment]
@Ceredron Er dette en reell problemstilling nå?

**Comment by ToreMasoy** [comment]
Utført for lenge siden.
