### ISSUE TITLE
Overgangsløsning A2: Implementer BrokerBridge i BrokerService AltinREST

### ISSUE THREAD

**Issue by RagnarFatland-Avanade** [Altinn/altinn-broker#257]
Implementer endringer i Altinn 2 REST-implementasjonen av BrokerService til å korrekt rute kall tilhørende synkroniserte formidlingstjenester til BrokerBridge.
Majoriteten av disse endringene er allerede utført som konsekvens av endringer i #256 så denne oppgaven bør tas etter den er ferdigstilt, bør stort sett omfatte utvidelse av unit tester o.l.

AltinnWebAPI.Controllers.BrokerServiceController.cs

- GetInbox
  - Endring i kalte BrokerSI.GetAvailableFiles
- GetInboxByReference
  - Endring i kalte GetBrokerServiceFileMetadataDataByReference / BrokerSI.GetBrokerServiceFileMetadata 
- GetBrokerServiceFileMetadataDataByReference
  - Endring i kalte BrokerSI.GetBrokerServiceFileMetadata
- DownloadFile
  - Endring i kalte GetInboxDownloadFileByReference
- GetInboxDownloadFileByReference
  - Endring i kalte GetFilenameByReference og BrokerSI.DownloadFileStreamed  
- GetFilenameByReference
  - Endring i kalte BrokerSI.GetFilenameByReference
- ConfirmDownloaded
  - Endring i kalte GetReceiptByReference
- GetHasAvailableFiles
  - Endring i kalte BrokerSI.CheckIfAvailableFiles
- PostOutboxUploadFileToBrokerService
  - Endring i kalte BrokerSI.InitiateBrokerService, BrokerSI.UploadFileStreamed
- GetBrokerServiceFileMetadataDataByReference
  - Endring i kalte BrokerSI.GetBrokerServiceFileMetadata
```[tasklist]
### Tasks
- [ ] #366
- [x] Bug - ConfirmDownload in Altinn 2 causes error when called from Rest. This seems to be related to Receipt handling.
- [x] Bug - Receipt handling calls in Altinn 2 Rest do not return data when calling data from Altinn 3.
- [x] Bug - Fixed Receipt to handle Altinn 3 files, however now we are getting error from Altinn3Bridge that file does not exist. However - when clicking calling "ConfirmDownload" not only is status updated in Altinn 3, the Altinn 3 receipt is returned. And those two calls are using the same Altinn 2 code.
- [x] ConfirmDownload returns receipt wiht Status: "ValidationFailed." This status should be "Ok"
- [x] Bug - Etter at sluttbruker har valgt "ConfirmDownload" og henter "receipt" via Rest er teksten fremdeles "File has been made available for download". Burde vært "File downloaded"?
```
