### ISSUE TITLE
Åpent møte, februar 24

### ISSUE THREAD

**Issue by hansdragnes** [Altinn/altinn-broker#265]
```[tasklist]
### Tasks
- [ ] Bestemme innhold (showcase)
- [ ] Lage underlag for innhenting av tilbakemeldinger
```

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-broker/issues/275
- [ ] Internoppgave 2
```
Utføres i oppgave #217
