### ISSUE TITLE
Flytt infrastrukturkode til hovedrepo

### ISSUE THREAD

**Issue by Ceredron** [Altinn/altinn-broker#295]
### Description

Etter litt frem og tilbake har organisasjonen landet på at vi bør samle infra/kode i et repo. Vi bør derfor flytte koden fra altinn-broker-infra til altinn-broker.

Merk! Dette gjør all infrastrukturen åpen for offentligheten. Vi bør derfor ta både en og to runder for å sikre at vi ikke lekker noen hemmeligheter eller åpner noen angrepsvektorer.

Dette fører også til at vi bør skrive om Github actionen vår for bygg/deploy til en action. Ta inspirasjon fra dialogporten (særlig mtp hvordan de har "approval"-steg før utrulling til produksjonsmiljø). Konsolider også de to Github actionene i en og bruk Github environments for å håndtere forskjellige miljø.

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-broker/issues/343
- [x] Skriv om Github Action
- [x] Skriv om dokumentasjonen slik at den er passende for allmenheten
- [ ] https://github.com/Altinn/altinn-broker/issues/341
```

**Comment by Andreass2** [comment]
Trenger tilgang til GITHUB_TOKEN og SONAR_TOKEN for å sette opp sonarcube og test. Kommenterer ut så lenge

**Comment by Ceredron** [comment]
Kjør igjennom code review med sikkerhet for å avklare:
* Hvordan bør vi konfigurere Github secrets så de ikke lekker ut
* Har vi feilkonfigurert noe sted
