### ISSUE TITLE
Oversetting og QA broker docs

### ISSUE THREAD

**Issue by leogasnier** [Altinn/altinn-broker#355]
Broker docs må oversettes til norsk og vi må få bort TBDs og sikre en konkret og praktisk tilnærming til at dokumentasjonen vår oppfyller sitt formål.

Lag separate issues for mangler du finner på veien dersom du ikke kan fikse det "on the fly".
```[tasklist]
### Tasks
- [ ] sjekk hvilke A2 docs vi må oppdatere
- [ ] samarbeidsportalen
- [x] github vs. A3 docs
- [x] Oversette til norsk
- [x] Lese docs - klarspråk, kommafeil, prioritering av innhold ift. kunde
- [x] sjekke lenker
```
Hvilke A2 områder må vi oppdatere mtp. overgangsløsning
Hvilke områder på samarbeidsportalen må vi fokusere på (prosjekt og produkt)
Hva ligger på github (readme) og hva ligger i docs
Generelle områder på docs kontra "våre"

**Comment by erikhag1** [comment]
Opprinnelig oppgave om "oversetting og QA" anses som ferdig og kan lukkes, men andre tasks som er lagt til her bør slettes her og overføres til en eller flere andre issues. TBD.

**Comment by erikhag1** [comment]
Se også #457 om overgang til ny innholdsstruktur for dokumentasjone iht. DIataxis. QA bør gjøres på #457 - glem denne?

**Comment by leogasnier** [comment]
A3 aspektet er i boks for nå. Lager ny issue for videre arbeid mot samarbeidsportalen og A2 docs.
