### ISSUE TITLE
Handling of Virus-scan result in Altinn 3 for Status in Altinn 3 and Altinn 2

### ISSUE THREAD

**Issue by tomshag** [Altinn/altinn-broker#409]
Når en file feiler i Altinn 3 pga. virus scanning, og vi så henter status i Altinn 2, så får vi status "File Deleted".
Dette gir avsender og mottaker feil ide om hva som har skjedd.
Tar en analyse av følgende.
```[tasklist]
### Tasks
- [x] sjekk Altinn 3 kode for hvordan status failed behandles. (Blir fil så gitt status deleted? Hvordan skal vi ordne det til å gi status failed.)
- [x] sjekk Altinn 2 kode for hvordan status vil bli oversatt.
- [x] se mulighet for å legge til File Status Text på Receipt text verdi når man ber om receipt i Altinn 2 slik at man får med "Failed" status fra Altinn 3.
```

**Comment by tomshag** [comment]
Task 1- 
Når Status på virus-scanning er "Virus funnet" eller lignende, altså failed, gis fil først status "Failed".
Deretter legges det en kø-jobb for å "Expire" fila.
Her blir fila så slettet og status settes til "Slettet".
Foreslått endring: En ny variabel i ExpireFileTransferCommandRequest som gjør det klart at fil skal "Expires" pga. feil under behandling, og derfor ikke skal gi status "Deleted", siden dette er en status som settes for filer som har gått igjennom hele Broker processen. (Altså lastet opp, behandlet, published, lastet ned og så evt. expired.)

**Comment by tomshag** [comment]
Pull request opprettet for endring basert på mail korrespondanse

**Comment by tomshag** [comment]
Handling of Altinn 2 code is now updated and returns full malwar error.
