### ISSUE TITLE
Hva skal planfasen inneholde?

### ISSUE THREAD

**Issue by ToreMasoy** [Altinn/altinn-broker#44]
```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-broker/issues/46
- [ ] https://github.com/Altinn/altinn-broker/issues/43
- [ ] https://github.com/Altinn/altinn-broker/issues/42
- [ ] https://github.com/Altinn/altinn-broker/issues/113
- [ ] https://github.com/Altinn/altinn-broker/issues/50
- [ ] https://github.com/digdir/portfolio/issues/48
```

**Comment by leogasnier** [comment]
https://github.com/digdir/portfolio: 
Planlegging
Saker beskrives og detaljeres slik at det skal være mulig å kunne iverksette og følge opp tiltaket. Tiltak flyttes til implementering når følgende er innfridd.

milepæler er definert
Arkitektur, Sikkerhet og juridisk er detaljert ytterligere fra konseptfasen
interne ressurser for å gjennomføre tiltaket er allokert
budsjett implementering og fordeling av budsjettbehov på ulike poster
organisering for å overta forvaltning og drift er beskrevet
