### ISSUE TITLE
Oppdater A3 docs - Kompetanse og innhold

### ISSUE THREAD

**Issue by leogasnier** [Altinn/altinn-broker#48]
Dokumentasjonen (på https://docs.altinn.studio) må oppdateres både på kort og lang sikt. Det første innholdet som må på plass er mer korrekte datoer både når det gjelder migrering og utvikling.

Dette skal også være stedet for brukerdokumentasjon og systemdokumentasjon. Vi må tidlig bygge rammeverket for dette.
Grunnleggende kunnskap i markdown og bruk av git, er et must for å komme i gang.

===============================
Fra Siv - kunne du gått inn på denne siden og sett på hva som står om migreringsstrategi for meldingstjeneste og formidlingstjeneste (https://docs.altinn.studio/authorization/migration/servicemigrationplan/#meldingstjenester) og  https://docs.altinn.studio/authorization/migration/servicemigrationplan/#formidlingstjenester. Det som står skrevet nå er noe jeg "gjettet" i november 2022 - antagelig kan det oppdateres med annen informasjon nå. 
```[tasklist]
### Tasks
- [x] Tore: Hvordan bruker vi git og markdown for å få endret dokumentasjonen
- [x] Leo: Produser innhold
- [ ] https://altinn.github.io/docs/api/api-migration/rest-sbs/sende-motta-filer/
- [ ] opplegg for oversettelse -> copilot?!
- [x] gjennomgang av oppskrift på dokumentering
```

**Comment by ToreMasoy** [comment]
Tore får først opplæring i GitHub og viser Leo

**Comment by ToreMasoy** [comment]
Har kommet litt i gang med rammeverk for dokumentasjon. Tenker at har ei egen mappe for broker og en for correspondence.

Har derfor laget https://docs.altinn.studio/broker/ men kun på egen branch. Skal vi ta utgangspunkt (struktur) i https://docs.altinn.studio/authorization/ eller ha annen oppdeling?

**Comment by leogasnier** [comment]
Api-endringsdocs: https://altinn.github.io/docs/api/api-migration/

**Comment by ToreMasoy** [comment]
Tore kaller inn til nytt møte for å se på fordeling av dokumentasjon på personer. Og struktur.

**Comment by ToreMasoy** [comment]
Tore og Erik lager oppskrift.

**Comment by CWO79** [comment]
@ToreMasoy bør du undersøke om vi kan få til en god og automatisert oversettelse av dokumentasjon fra norsk til engelsk. Evt. kan vi kanskje få hjelp av Hans til å lage et script?
