### ISSUE TITLE
Oppdater dokumentasjon for utvikleroppsett

### ISSUE THREAD

**Issue by Ceredron** [Altinn/altinn-broker#480]
**Beskrivelse**

Readme'en vår i Broker har ikke fått særlig oppmerksomhet på en stund. Sørg for at det er klart for nye utviklere over sommeren. Gjør samtidig vårrengjøring i prosjektfilene. 
```[tasklist]
### Tasks
- [x] Gjennomgå og fiks readme.md (dokumentasjon for utvikleroppsett)
- [x] Gjør pipeline grønn
- [x] Sørg for at alle miljøer er migrert riktig (reset hvis nødvendig, informer i så tilfelle Kartverket for staging)
- [x] Fiks navngivning og struktur for "Test"-mappa (og docs?)
- [x] Dokumenter hvordan CI/CD henger sammen
- [x] Fjern Hangfire dashboard prosjekt?
- [x] Fjern .vscode-mappe?
- [ ] Test at Postman-collectionen fungerer
- [x] Verifiser om OpenAPI-speccen i repoet er oppdatert
```
