### ISSUE TITLE
Analysere bruksmønstre, kostnader mv.

### ISSUE THREAD

**Issue by erikhag1** [Altinn/altinn-broker#61]
## Users view

Title: **Analysere bruksmønstre, kostnader mv.**
User role(s): Kunde
Users value statement(s): 
TBD

#### High level features (capabilities):
 * Analysere bruksmønstre, kostnader mv.
#### Additional information
TBD

```[tasklist]
### Features 
- [ ] Generere statistikk
- [ ] Analysere historikken (ut fra statistikk)  
- [ ] Presentere historisk innsikt gjennom GUI
- [ ] Presentere historisk innsikt gjennom rapporter
- [ ] Gi tilgang til rapporter gjennom API
```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 2_
_Stage: Maintenance_
_ArchiConceptID: id-1d4535e6d9b84337a7724354a8737e08_
_GithubIssueID: I_kwDOIwEQMM5vYMil_

**Comment by erikhag1** [comment]
Leveringstid, åpningsgrad, tid fra mottatt til åpnet.
NB: Husk fakturagrunnlag;  uatomatisk fakturering

**Comment by RagnarFatland-Avanade** [comment]
Bør slås sammen med #63  ?
@erikhag1

**Comment by Viktorolsen** [comment]
Se sak 620 på correspondance
