### ISSUE TITLE
Lett forståelig og strukturert fakturagrunnlag

### ISSUE THREAD

**Issue by erikhag1** [Altinn/altinn-broker#63]
## Users view

Title: **Lett forståelig og strukturert fakturagrunnlag**
User role(s): Kunde
Users value statement(s): 
* Det gjør det enklere for økonomiavdelingen å utføre sitt arbeid effektivt. Reduserer tid og ressurser brukt på fakturahåndtering og mulighet for automatisering av fakturabehandling.
* Forebygger misforståelser og feil. 

#### High level features (capabilities):
 * Støtte for effektiv fakturabehandling
#### Additional information
TBD

```[tasklist]
### Features 
- [ ] Transaksjonslogg
- [ ] Statistikk som viser trend i transaksjonsvolum
- [ ] Spesifisert fakturagrunnlag for manuell behandling
- [ ] Spesifisert fakturagrunnlag for maskinell behandling
- [ ] Samlet faktura fra Digdir/Altinn
```

```[tasklist]
### Work items
- [ ] Design Transaksjonslogg database / tabell - ses i forhold til krav om å kunne bli glemt (#63)
```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 4_
_Stage: Onboarding_
_ArchiConceptID: id-64613d290c4a42bf807898b4978d5d9f_
_GithubIssueID: I_kwDOIwEQMM5vYMjX_

**Comment by erikhag1** [comment]
NB: Ikke kryssfinansierng!

**Comment by leogasnier** [comment]
Formidling fakturagrunnlag frem til 31.12.2026 - hver forsendelse telles som en transaksjon -> Rapport pr. mnd: miljø (TT02 og PROD), antall instansierte forsendelser, fra hvem, til hvem, størrelse - vi må beskrive en månedsrapport for formidling som holder mål og gir oss fakturagrunnlag inntil videre.

trengs kun prod i første omgang (men test er vel greit for vår del).

vil ligge til grunn for fakturering av nye kunder frem til 31.12.2026 - eksisterende betaler iht. dagens innplassering.

**Comment by Viktorolsen** [comment]
Se sak 620 på correspondance
