### ISSUE TITLE
Finne og velge riktig mottakeradresse

### ISSUE THREAD

**Issue by erikhag1** [Altinn/altinn-broker#64]
## Users view

Title: **Finne og velge riktig mottakeradresse**
User role(s): Avsender
Users value statement(s): Ved å enkelt kunne finne og velge den riktige mottakeradressen, sparer jeg tid og unngår frustrasjon. Dette gir meg trygghet i at mine sendinger alltid når frem til den rette destinasjonen uten feil eller forsinkelser.

#### High level features (capabilities):
 * Støtte oppslag i felles adresse- og kapabilitetsregister
#### Additional information
TBD

```[tasklist]
### Features 
- [ ] Oppslag i mottakerregister som Altinn-tjeneste
- [ ] Valg av mottakere ut fra meldingstype basert på kapabilitet og autorisasjon
- [ ] Integrert adresseregister på tvers av sektorene, samt eventuelt ulike mottakerregistre (eks. politiets nåværende mottakerregister)
```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 5_
_Stage: Operation_
_ArchiConceptID: id-68c4cf89eb064043a41faf71dfb96b8c_
_GithubIssueID: I_kwDOIwEQMM5vYMju_

**Comment by erikhag1** [comment]
Avhengig av kontekst? I mange tilfeller vet avsender hvem som er mottaker

**Comment by leogasnier** [comment]
usikker på relevans - fint om behovet kan beskrives ytterligere @erikhag1

**Comment by Andreass2** [comment]
@Viktorolsen @ToreMasoy 

Denne tenker jeg kan lukkes, og så heller opprettes dersom behovet oppstår på nytt og man kan gjøre en vurdering på nytt. Dette vil falle på utsiden av moderniseringsscopet
