### ISSUE TITLE
Forstå veikart for løsninger som jeg har eller vurderer å anskaffe

### ISSUE THREAD

**Issue by erikhag1** [Altinn/altinn-broker#65]
## Users view

Title: **Forstå veikart for løsninger som jeg har eller vurderer å anskaffe**
User role(s): Kunde
Users value statement(s): 
Ved å tydelig forstå veikartet for løsningene vi enten allerede benytter eller vurderer å anskaffe, kan vår organisasjon proaktivt planlegge for fremtiden, optimalisere ressursallokering, og sikre at våre teknologiske investeringer er i tråd med både nåværende og fremtidige forretningsbehov. Dette muliggjør informerte beslutningsprosesser.

#### High level features (capabilities):
 * Kommunisere  produktstrategi og veikart
#### Additional information
TBD

```[tasklist]
### Features
- [x] Produktgruppestrategi
- [ ] Produktstrategi og veikart
- [ ] Kommunikasjon
```

```[tasklist]
### Work items
- [ ] https://github.com/Altinn/altinn-broker/issues/113
- [ ] https://github.com/Altinn/altinn-broker/issues/50
```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 6_
_Stage: Onboarding_
_ArchiConceptID: id-46257514d26c4823ab0afbf488827286_
_GithubIssueID: I_kwDOIwEQMM5vYMkG_

**Comment by erikhag1** [comment]
Formidler/løsningsleverandør: Gi forutsigbarhet i utviklingen av løsningen
