### ISSUE TITLE
[7-Kunde] Forutse kostnader for etablering og drift av løsningen for aktuelle behov

### ISSUE THREAD

**Issue by erikhag1** [Altinn/altinn-broker#66]
## Users view

Title: **Forutse kostnader for etablering og drift av løsningen for aktuelle behov**
User role(s): Kunde
Users value statement(s): 
* Ressurs og kompetanse behov: hva trengs for å ta i bruk løsningen?
*  Gevinstanalyse

## Vendors view

High level features (capabilities):
 * Støtte for kalkyle av kostnader for etablering og drift av løsningen

```[tasklist]
### Features 
- [ ] Produktkalkulator for selvbetjent kalkyle
- [ ] Oversikt over opsjoner og SLA-nivåer
- [ ] Produktpakker med standardvalg av opsjoner og SLA-nivåer
- [ ] Støttefunksjon/salg
```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 7_
_Stage: Onboarding_
_ArchiConceptID: id-9a8d6b4eb09046f3898583e2d67483dc_
_GithubIssueID: [to be autofilled]_

**Comment by erikhag1** [comment]
Husk: Kostnad for kjøring av jobber i Azure må dokumenteres  Ved utvikkling

**Comment by Ceredron** [comment]
@leogasnier Har vi gjort denne?

**Comment by Viktorolsen** [comment]
Lukkes da dette delvis tilhører marked.
