### ISSUE TITLE
[8-Mottaker] Få gjentatt oversendelse av komplett dokumentsamling på forespørsel

### ISSUE THREAD

**Issue by erikhag1** [Altinn/altinn-broker#67]
## Users view

Title: **Få gjentatt oversendelse av komplett dokumentsamling på forespørsel**
User role(s): Mottaker
Users value statement(s): 
TBD

## Vendors view

High level features (capabilities):
 * Støtte gjentatt oversendelse av hele dokumentsamlingen

```[tasklist]
### Features 
 - [ ] Resending  av  hele dokumentsamlingen  samlet, på forespørsel fra mottaker (siste versjon)
- [ ] Overendelse av  hele pakken samlet på forespørsel fra andre enn opprinnelige mottakere
- [ ] Valg av tidligere versjoner vs. siste versjon

```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 8_
_Stage: Operation_
_ArchiConceptID: id-f42d6e359c7f40eba1544ad11a5a79d5_
_GithubIssueID: [to be autofilled]_

**Comment by erikhag1** [comment]
Resending vs. Innhenting; oppdatert versjon 
Bakrgunn for versjonering: Saksgrunnlag på gitt tidspunkt
Alternativ: Vi komuniserre behovet fra mottaker til avsender

**Comment by RagnarFatland-Avanade** [comment]
Dersom mottaker har kvittert OK, så er mest sannsynlig data sanert. Vi må nok derfor regne med at melding må videreformidles til avsender.
Hvis dette er en en vanlig problemstilling, kan man vurdere en delay mellom kvittert mottatt og sanering, feks definert per Formidlingstjeneste.
