### ISSUE TITLE
Identifisere at det er endringer i mottatte filer

### ISSUE THREAD

**Issue by erikhag1** [Altinn/altinn-broker#69]
## Users view

Title: **Identifisere at det er endringer i mottatte filer**
User role(s): Mottaker
Users value statement(s): 
TBD

#### High level features (capabilities):
 * Spore endringer i mottatte filer 

#### Additional information
TBD

```[tasklist]
### Features
- [x] Støtte for versjonsmerking av filer fra avsender
- [x] Endringslogg per pakke/dokumentsamling
- [x] Støtte for spørringer mot endringslogg
```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 10_
_Stage: Operation_
_ArchiConceptID: id-18f62ded9d494ef8b95a25df5f00ccdc_
_GithubIssueID: I_kwDOIwEQMM5vYMlw_

**Comment by erikhag1** [comment]
Juridiske betenkeligheter?
I stedet: Avsender kan versjomsmerke 
Forsendelseid + påtegningsid?
Verifiser hash

**Comment by leogasnier** [comment]
Løses ved bruk av HASH - filer kan ikke endres.
