### ISSUE TITLE
Løpende innsikt i  status om levering, mottak og lesing av forsendelser

### ISSUE THREAD

**Issue by erikhag1** [Altinn/altinn-broker#75]
## Users view

Title: **Løpende innsikt i  status om levering, mottak og lesing av forsendelser**
User role(s): Avsender
Users value statement(s): 
Å vite nøyaktig når en forsendelse er levert, mottatt eller lest, gjør det lett å følge med på forsendelsen, og resultatet kan brukes som input til å starte andre prosesser og aktiviteter.  Mottakere som venter på viktig informasjon vil sette pris på å kunne få oppdateringer om statusen på sine forsendelser.

#### High level features (capabilities):
 * Sanntids sporing av status om levering, mottak og lesing av forsendelser

#### Additional information
TBD

```[tasklist]
### User stories
- [ ] https://github.com/Altinn/altinn-broker/issues/106
- [x] Logging via Application Insights. NB: Bør være fellesløsning.
- [ ] https://github.com/Altinn/altinn-broker/issues/223
- [x] API for å forespørre status (har det i dag for kvitteringer) - Støttet i GetFileOverview i API
- [ ] GUI for sporing av meldinger
- [ ] GUI for saksgang (via Altinn Studio, Dialogporten)?
- [ ] https://github.com/Altinn/altinn-broker/issues/400
```

```[tasklist]
### Work items
```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 16_
_Stage: Operation_
_ArchiConceptID: id-e5a01df6c4db4f398541a0f717c414cd_
_GithubIssueID: I_kwDOIwEQMM5vYMtC_

**Comment by erikhag1** [comment]
Sanntids sporing av status om levering, mottak og lesing av forsendelser

**Comment by Viktorolsen** [comment]
Resterende er flyttet til #87
