### ISSUE TITLE
Minst mulig arbeid og kostnader ved overgang til nye løsninger og grensesnitt for formidlingstjenesten

### ISSUE THREAD

**Issue by erikhag1** [Altinn/altinn-broker#76]
## Users view

Title: **Minst mulig arbeid og kostnader ved overgang til nye løsninger og grensesnitt i formdlingstjenesten**
User role(s): Tjenesteeiere og avsendere/mottakere
Users value statement(s): 
Ved å sikre minimalt arbeid og kostnader ved overgang til ny løsning og grensesnitt i formidlingstjenesten, gis organisasjonen mulighet til å oppdatere uten å pådra seg store driftsforstyrrelser eller budsjettoverskridelser. Dette reduserer overgangsrisikoer, og gir oss mulighet til raskt å tilpasse oss ny løsning, samtidig som vi opprettholder kontinuerlig drift og servicekvalitet.

#### High level features (capabilities):
 * Enkel overgang til ny løsninger  og versjoner
#### Additional information
TBD

```[tasklist]
### Features
- [x] Brøytekjøring sammen med utvalgte kunder og partnere/konsulenter
- [ ] https://github.com/Altinn/altinn-broker/issues/393
- [ ] Automatiserte overgangsrutiner (instllasjonsjobber mv.)
- [ ] Pekere til gode eksemepler/ god praksis
- [x] Dokumentasjon, veiledning og kommunikasjon (informasjonsmøter
- [ ] https://github.com/Altinn/altinn-broker/issues/197
- [ ] https://github.com/Altinn/altinn-broker/issues/74
- [ ] https://github.com/Altinn/altinn-broker/issues/203
```

```[tasklist]
### Work items
- [ ] https://github.com/Altinn/altinn-broker/issues/133
```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 17_
_Stage: Migration_
_ArchiConceptID: id-13d9833c428d4ae88636a41772554305_
_GithubIssueID: I_kwDOIwEQMM5vYMta_

**Comment by Viktorolsen** [comment]
Kan du gi en status på denne? @erikhag1
