### ISSUE TITLE
Motta varsel om  forsendelse

### ISSUE THREAD

**Issue by erikhag1** [Altinn/altinn-broker#78]
## Users view

Title: **Motta varsel om  forsendelse**

Det må være støtte for varsling av forsendelser via events og/eller sms/epost
User role(s): Mottaker
Users value statement(s): 
Ved å motta varslinger om forsendelser, får jeg som mottaker øyeblikkelig og pålitelig informasjon direkte tilgjengelig. Dette betyr at jeg kan handle raskt, være oppdatert og sikker på at jeg ikke går glipp av viktig informasjon. Det gjør det enklere for meg å planlegge, svare, og engasjere meg, hvilket fører til økt tillit og tilfredshet med avsender.

#### High level features (capabilities):
 * Gi varsel om  forsendelse
#### Additional information
TBD

```[tasklist]
### Features
- [x] Notifikasjon til mottaker system via Event (MVP+1)
- [ ] https://github.com/Altinn/altinn-broker/issues/89
- [ ] https://github.com/Altinn/altinn-broker/issues/136
```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 19_
_Stage: Operation_
_ArchiConceptID: id-ae44593ed2c94ef6998fa6a416c56ca5_
_GithubIssueID: I_kwDOIwEQMM5vYMuI_

**Comment by erikhag1** [comment]
Nye teknologier i setdet for sms og e-pos for varsling?
Løsning for notifikasjon: Altinn events?

**Comment by leogasnier** [comment]
@Ceredron - kan notifikasjon via events ansees som løst? (se beskrivelse på denne issuen)?

**Comment by RagnarFatland-Avanade** [comment]
Avventer reelt behov for SMS/Epost-varsling.
