### ISSUE TITLE
Oppdage forsinkede  og mislykte forsendelser

### ISSUE THREAD

**Issue by erikhag1** [Altinn/altinn-broker#79]
## Users view

Title: **Oppdage forsinkede  og mislykte forsendelser**
User role(s): Avsender 
Users value statement(s): 
TBD

#### High level features (capabilities):
 *  Feilhåndtering for forsinkede og mislykte forsendelser
#### Additional information
TBD

```[tasklist]
### Features
- [x] Varsle avsender om mislykket levering (med forståelig feilmeldig) (MVP)
- [x] Varsle avsender om at mottaker ikke har hentet fil innen deadline
- [ ] Varsle avsender om sen levering ift. SLA
- [ ] Registrere resultat av avsenders eventuelle alternative leveringsforsøk (f.eks. på minnepinne)
- [ ] https://github.com/Altinn/altinn-broker/issues/476
```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 20_
_Stage: Operation_
_ArchiConceptID: id-284f5297ab634d3da4b63089596ff281_
_GithubIssueID: I_kwDOIwEQMM5vYMul_

**Comment by RagnarFatland-Avanade** [comment]
Gjelder dette events til datasystemer, eller epost/sms-varsel til personer som representerer? @erikhag1 @leogasnier 
Det er allerede støttet at dette vises i FileStatus dersom de kaller APIet for å hente det ut.

**Comment by leogasnier** [comment]
Vi snakker via statusAPI i første omgang - Event på mislykket forsendelse er selvsagt også relevant men kommer kanskje seinere? Vi må jo også definere hvilke events vi skal ha i det store og hele. Så litt på issuen Rune TL delte på slacken vår nå i kveld og den var særdeles godt strukturert mtp. hva som skal logges og hvordan.

**Comment by Ceredron** [comment]
Støttet via både events og polling
