### ISSUE TITLE
Oversikt over tidligere transaksjoner for levering , mottak og lesing av forsendelser

### ISSUE THREAD

**Issue by erikhag1** [Altinn/altinn-broker#80]
## Users view

Title: **Oversikt over tidligere transaksjoner for levering , mottak og lesing av forsendelser**
User role(s): Avsender
Users value statement(s): 
Å ha en detaljert oversikt over statuser for gjennomførte forsendelser kan være verdifull for revisjonsformål, som juridisk dokumentasjon og som input til å forbedre min tjeneste.
Separat datalager/datavarehus?

#### High level features (capabilities):
 * Gi oversikt over tidligere transaksjoner for levering, mottak og lesing av forsendelser
#### Additional information
TBD

```[tasklist]
### Features
- [ ] https://github.com/Altinn/altinn-broker/issues/279
- [x] API - spørring mot historisk logg
- [ ] GUI for visning av historikk
```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 21_
_Stage: Maintenance_
_ArchiConceptID: id-9e52397b1f51481c9b4e36f153eb4f0a_
_GithubIssueID: I_kwDOIwEQMM5vYMu7_

**Comment by erikhag1** [comment]
Flere grunner, blant annet juridisk - korrekt bevismateriale….

**Comment by ToreMasoy** [comment]
Skal innholdet i loggen eksistere for alltid? Eller skal vi allerede fra starten av informere om at loggen kun inneholder informasjon om de eksempelvis tre siste årene?
