### ISSUE TITLE
Selvbetjent konfigurasjon av tjeneste

### ISSUE THREAD

**Issue by erikhag1** [Altinn/altinn-broker#81]
## Users view

Title: **Selvbetjent konfigurasjon  av opsjoner i  løsningen**
User role(s): Kunde/Tjenesteeier
Users value statement(s): Vår organisasjon raskt og effektivt tilpasse løsningen til våre unike arbeidsflyter og krav. Dette gir oss muligheten til å optimalisere prosesser, øke produktiviteten og sikre at verktøyet alltid er i takt med vår skiftende forretningskontekst uten å vente på ekstern bistand. 

#### High level features (capabilities):
 * Støtte for selvbetjent oppsett av løsningen
#### Additional information
TBD

```[tasklist]
### Features
- [ ] https://github.com/Altinn/altinn-broker/issues/201
- [ ] https://github.com/Altinn/altinn-broker/issues/350
- [x] Produktpakker med standardvalg av opsjoner og SLA-nivåer
- [x] Produktkalkulator
- [ ] https://github.com/Altinn/altinn-broker/issues/60
- [ ] https://github.com/Altinn/altinn-broker/issues/244
- [ ] https://github.com/Altinn/altinn-broker/issues/267
- [ ] https://github.com/Altinn/altinn-broker/issues/278
- [ ] https://github.com/Altinn/altinn-broker/issues/337
- [ ] https://github.com/Altinn/altinn-studio/issues/12530
```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 22_
_Stage: Preparation_
_ArchiConceptID: id-a3ef367ea0c84bb39aee7bf3c756ffcb_
_GithubIssueID: I_kwDOIwEQMM5vYMvS_

**Comment by tomshag** [comment]
Min forståelse er at Tjenestekonfigurasjonen skal gjøres i Resource Registry (RR). 
(https://docs.altinn.studio/authorization/modules/resourceregistry/)

Vil en konfigurator bli opprettet som en del av utviklingen av RR?

**Comment by Ceredron** [comment]
Løst av ressursregister GUI.
