### ISSUE TITLE
Sende filsamlinger med mulighet for samlet og enkeltvis levering og oppfølging av status

### ISSUE THREAD

**Issue by erikhag1** [Altinn/altinn-broker#82]
## Users view

Title: **Sende filsamlinger med mulighet for samlet og enkeltvis levering og oppfølging av status **
User role(s): Avsender
Users value statement(s): 
TBD

#### High level features (capabilities):
 * Formidle filsamlinger med støtte  for både samlet og enkeltvis levering og oppfølging av status
#### Additional information
TBD

```[tasklist]
### Features
- [ ] Overføre enkeltfiler i større pakker
- [ ] Pakking av enkeltfiler i større pakker (inkl. signeing av pakken)
- [ ] Utpakking av enkeltfiler før levering
- [ ] Levere en og en fil i større pakker
```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 23_
_Stage: Operation_
_ArchiConceptID: id-8a86f7f76bf24c1c9f06b2be758e79d3_
_GithubIssueID: I_kwDOIwEQMM5vYMvx_

**Comment by erikhag1** [comment]
Metadata med if som knytter sammen filer til en samling. Dessuten metadata som muliggjør f.eks. versjonsmerking (enten nasjonal standard, industristandard eller bilaterale avtaler, ev. tjenesteeier)

**Comment by RagnarFatland-Avanade** [comment]
@ToreMasoy en mappe er (avhengig av filsystem) bare en gruppering av filer. Det vanligste når man sender en mappe med filer er å lage ett arkiv (feks zip) som inneholder hele strukturen, og sende det som en strøm.
Men det er seff. mulig jeg tar feil..

**Comment by tomshag** [comment]
- Pakking av enkeltfiler i større pakker (inkl. signeing av pakken)
Denne virker som hvordan BrokerService fungerer idag per standard. 1-flere filer leveres i en zip pakke.

- Utpakking av enkeltfiler før levering
Dette er jeg ikke sikker på hva betyr. Betyr dette for eksempel at Altinn kan motta en zip fil, og at vi som en tjeneste skal kunne pakke ut en enkel fil fra pakken og returnere den til mottaker?

- Overføre enkeltfiler i større pakker
- Levere en og en fil i større pakker
Betyr dette at for eksempel Altinn skal motta en zip fil eller skal vi ha en logisk idè om en "Pakke" som inneholder flere filer som vi så kan returnere en og en?


Dersom vi skal kunne motta en zip fil og returnere individuelle filer i zip fila så betyr det at vi enten må 

1. Lagre 2 versjoner, zip fila, og individuelle filer og returnere basert på brukers ønske
eller
2. Gjøre utpakking av zip fila hver gang man ønsker å hente ut en individuell fil
eller
3. Lagre kun individuelle sub filer i zip fila og pakke disse til en zip når det ønskes å hente alle filer. (Som virker mest naturlig, selv om det vil ta mer tid å faktisk pakke filene før de returneres, det må også lages en slags trash-cleanup for å sikre at vi ikke lagrer pakkene når de ikke lenger trengs).

**Comment by RagnarFatland-Avanade** [comment]
TODO: @RagnarFatland-Avanade oppdaterer til å reflektere POC: Forsendelse med mange filer.
Splitting/Joining tas i en egen (lav-prio) epic.

**Comment by RagnarFatland-Avanade** [comment]
Kan mest sannsynlig løses ved bruk av Dialogporten til å gruppere flere Broker-forsendelser i samme dialog.
