### ISSUE TITLE
Sende og motta store filer

### ISSUE THREAD

**Issue by erikhag1** [Altinn/altinn-broker#83]
## Users view

Title: **Sende store filer til en eller flere mottakere **
User role(s): Avsender
Users value statement(s): 
Ved å kunne sende store filer til en eller flere mottakere sikrer jeg effektiv og pålitelig overføring av viktig informasjon eller data. Dette eliminerer behovet for kompliserte "omveier", som f.eks oppsplitting av filer eller bruk av eksterne eller manuelle metoder for overføring av data (f.esk minnepinne). Med denne funksjonaliteten kan jeg sørge for at mottakere raskt får tilgang til nødvendige filer, noe som sparer tid, ressurser og øker produktiviteten for alle involverte parter

#### High level features (capabilities):
 * Formidle oversendendelse av store filer fra en avsender til en eller flere mottakere

#### Additional information
TBD

```[tasklist]
### Features
- [x] Levere meldinger til adresserte mottakere (MVP)
- [x] Event-basert statustilbakemelding (MVP+1)
- [ ] https://github.com/Altinn/altinn-broker/issues/523
- [ ] Adressering og ruting basert på felles adresse/kapabilitetsregister
- [x] Støtte pub-sub
- [ ] Logging av mottak også for events (ikke for lesing av events for Formidlingstjensten)
- [ ] https://github.com/Altinn/altinn-broker/issues/82
- [ ] https://github.com/Altinn/altinn-broker/issues/105
- [ ] https://github.com/Altinn/altinn-broker/issues/79
- [ ] https://github.com/Altinn/altinn-broker/issues/104
- [ ] https://github.com/Altinn/altinn-broker/issues/85
- [ ] https://github.com/Altinn/altinn-broker/issues/84
- [ ] https://github.com/Altinn/altinn-broker/issues/202
- [ ] https://github.com/Altinn/altinn-broker/issues/67
- [ ] https://github.com/Altinn/altinn-broker/issues/69
- [ ] https://github.com/Altinn/altinn-broker/issues/72
- [ ] https://github.com/Altinn/altinn-broker/issues/87
- [ ] https://github.com/Altinn/altinn-broker/issues/71
- [ ] https://github.com/Altinn/altinn-broker/issues/88
- [ ] https://github.com/Altinn/altinn-broker/issues/89
- [ ] https://github.com/Altinn/altinn-broker/issues/70
- [ ] https://github.com/Altinn/altinn-broker/issues/78
- [ ] https://github.com/Altinn/altinn-broker/issues/64
- [ ] Tilgjengeliggjøre formidlingstjenesten i dialogporten > "create dialogue"
- [ ] https://github.com/Altinn/altinn-broker/issues/420
- [ ] https://github.com/Altinn/altinn-broker/issues/525
```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 24_
_Stage: Operation_
_ArchiConceptID: id-e7b524d5fcc04edabf0db219d0d164fe_
_GithubIssueID: I_kwDOIwEQMM5vYMwG_

**Comment by erikhag1** [comment]
Det nye Rressursregisteret/RRR åpner for at tjenesteeiere kan lege inn logikk som f.eks. mottakerregister. Se også ELMA… Kan settes opp av mottaker (hva kan og vil jeg) og/eller tjenesteeier
* ang. pub-sub: push-varsel
* funksjonalitet for å sjekke status på prosess oppp mot koreografi

**Comment by RagnarFatland-Avanade** [comment]
"Støtte pub-sub"
Må grubles litt over; dersom fokus er sikkerhet, så bør avsender ALLTID vite hvem som kan motta forsendelsen før de sender.
Når jeg tenker Pub-Sub, så er mottakere ansvarlige for å sette opp subscriptions, og avsender publiserer kun meldingen uten å vite hvem som mottar.

**Comment by erikhag1** [comment]
Ang, pub-sub, så kreves det autorisasjon på mottak/sub. Tror dette er innbakt i Altinn Events, men må sjekkes nærmere.

**Comment by Ceredron** [comment]
Har blitt løst av andre saker (se referanser).
