### ISSUE TITLE
Sikre at dokumenter som utveksles ikke utsettes for brudd på  informasjonssikkerhet og personvern

### ISSUE THREAD

**Issue by erikhag1** [Altinn/altinn-broker#84]
## Users view

Title: **Sikre at dokumenter som utveksles ikke utsettes for brudd på  informasjonssikkerhet og personvern**
User role(s): Kunde
Users value statement(s): Ved å vite at dokumentene jeg utveksler håndteres med høyeste grad av informasjonssikkerhet og personvern, kan jeg dele og motta informasjon uten bekymringer. Dette gir tillit til at sensitive informasjon alltid er beskyttet mot uønsket tilgang eller lekkasje

#### High level features (capabilities):
 * Tilstrekkelig informasjonssikkerhet og personvern i formidlingsløsningene
#### Additional information
TBD

```[tasklist]
### Features
- [ ] https://github.com/Altinn/altinn-broker/issues/163
- [ ] Avklare muligheter, flyt og forholdet mellom formidling, dialogport og eformidling mtp. "chain of custody", sporbarhet.
- [ ] https://github.com/Altinn/altinn-broker/issues/177
- [ ] https://github.com/Altinn/altinn-broker/issues/271
- [ ] https://github.com/Altinn/altinn-broker/issues/191
- [ ] https://github.com/Altinn/altinn-broker/issues/306
- [ ] https://github.com/Altinn/altinn-broker/issues/316
- [ ] https://github.com/Altinn/altinn-broker/issues/455
- [ ] https://github.com/Altinn/altinn-broker/issues/537
```

```[tasklist]
### Work items

- [ ] https://github.com/Altinn/altinn-broker/issues/42
```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 25_
_Stage: Onboarding_
_ArchiConceptID: id-24fc84110aac4b589d7ab9a7066b7347_
_GithubIssueID: I_kwDOIwEQMM5vYMwW_

**Comment by erikhag1** [comment]
Husk: Juss, teknisk, merkantilt (salgbar sikkerhet - god og kostnads)

**Comment by RagnarFatland-Avanade** [comment]
"Sjekk av riktig filtype"
Er tanken https://en.wikipedia.org/wiki/File_verification eller kontroll av at filtypen er av ett angitt format? Jeg vil tro at vi i det lengste kan strekke oss til checksum/hash verfikasjon av filene, men det må graves litt i da man ofte må lese hele filen for å lage hash.

**Comment by leogasnier** [comment]
Obs! @erikhag1  - Mulig vi bør få inn noe på denne om forholdet mellom innholdsagnostisk, ende-til-ende kryptert og sikkerhetsfeatures. OG burde feature for å sikre mulighet til kobling til andre lagringsmedier her, ev. også egenskaper som muliggjør å kjøre hele applikasjonen på andre plattformer?

**Comment by leogasnier** [comment]
@erikhag1 - ønsker litt videre arbeid på denne frem mot produksjonsklar broker: 1. Avklare hvordan formidlingstjenester kan inngå i/konsumeres via dialogporten og ev. eFormidling slik at vi kan vurdere om det er noe vi prioriterer i år. 2. Ansiktsløfting på sikkerhetsdokumentasjon og juridiske avklaringer knyttet til mulighet for å skru av sikkerhetsfunksjoner ifbm. E2EE vs. vårt kontrollansvar som databehandler.

**Comment by Ceredron** [comment]
Gjenværende:
https://github.com/Altinn/altinn-correspondence/issues/649
