### ISSUE TITLE
Tilgang til brukerstøtte og veiledning

### ISSUE THREAD

**Issue by erikhag1** [Altinn/altinn-broker#86]
## Users view

Title: **Tilgang til brukerstøtte og veiledning**
User role(s): Kunde
Users value statement(s): 
* Enkelt å bruke løsningen
* Unngå feilsituasjoner
* Raskt å løse opp i feil eller problemer som eventuelt inntreffer

Ved å ha tilgang til brukerstøtte og veiledning føler jeg meg trygg i bruken av produktet. Dette sikrer at jeg enkelt kan løse utfordringer, få svar på spørsmål, og bruke systemet effektivt. Ved å ha rask og pålitelig hjelp tilgjengelig, kan jeg maksimere produktiviteten, redusere frustrasjon, og få mest mulig verdi ut av løsningen

#### High level features (capabilities):
 * Brukerstøtte og veiledning
#### Additional information
TBD

```[tasklist]
### Features
- [x] Brukerdokumentasjon
- [x] Teknisk support 24*7;)
- [ ] Spesialisttøtte (betalt).
- [ ] Støtte for eLæring
```

```[tasklist]
### Work items
- [x] Definere opplæringsløp, kom i gang på 123
- [x] Opprette brukermanual
- [x] Teknisk dokumentasjon
- [x] Utvikle FAQ med ofte stilte spørsmål og svar
- [x] Lag opplæringsvideo/ webinar
- [ ] Finn ut og beslutt gjennomføring av brukerundersøkelser
- [x] Etabler feedback prosess for forbedring og utvikling av våre produkter
- [x] Gjennomgang og kvalitetssikre dokumentasjon. Etabler det som fast rutine
```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 27_
_Stage: Maintenance_
_ArchiConceptID: id-033cd5c48bb4403f9f55ad3e5ad8090f_
_GithubIssueID: I_kwDOIwEQMM5vYMw__

**Comment by ToreMasoy** [comment]
Postman collection?

**Comment by Ceredron** [comment]
Dette har vi gjort. Kontinuerlig videreforbedres.
