### ISSUE TITLE
[28-Tjenesteeier] Tilrettelegge brukervennlige løsninger for å sende og motta store filer

### ISSUE THREAD

**Issue by erikhag1** [Altinn/altinn-broker#87]
## Users view

Title: **Tilrettelegge brukervennlige løsninger for å sende og motta store filer**
User role(s): Tjenesteeier
Users value statement(s): 
TBD

## Vendors view

High level features (capabilities):
 * Tilby brukervennlig løsning for å sende og motta store filer

```[tasklist]
### Features 
- [ ] Altinn GUI  for avsender
- [ ]  Drag&drop filer for opplasting
- [ ]  Framdriftsindikator for oppalastiing
- [ ]  Presentasjon av sanntids sporing i avsenders GUI
    - [ ] Hjelp-funksjon i GUI
- [ ]  Altinn GUI for mottaker
    - [ ] Drag&drop filer for nedlasting
    - [ ] Framdriftsindikator for opplastiing
    - [ ] Lesebekreftelse
```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 28_
_Stage: Onboarding_
_ArchiConceptID: id-b895cb2c76844c04bbf73edd50528a1b_
_GithubIssueID: [to be autofilled]_

**Comment by erikhag1** [comment]
Annet enn GUI?
Løsning kan omfatte f.els. Skreddersydd Altinn Studio app

**Comment by Ceredron** [comment]
@leogasnier Er denne fortsatt relevant?

**Comment by Ceredron** [comment]
Forhør med politiet om hva behovene deres knyttet til denne, og evaluer om Correspondence kan brukes istedet,

**Comment by leogasnier** [comment]
Denne er relevant ut fra både politiet og helse MR-case.

**Comment by ToreMasoy** [comment]
Nina Kylstad sitt innspill:
Jeg mener at dette er en komponent vi burde ha tilgjengelig for app'er i Studio ja. Jeg ser for meg at vi burde støtte både det å kunne legge formidling inn som en del av flyten i en ordinær "skjema"-app, og å tilby et tilpasset opplegg for de som kun skal ha et GUI for formidling. Dvs. f.eks. en spesialtilpasset mal med ferdig oppsett der man kun trenger å konfigurere noen ting.
Da kan man og (forhåpentligvis) utnytte tilgangsstyringen som er på plass i appene for å styre hvem som skal ha tilgang til å gjøre forskjellige aksjoner. Så må vi vel i tillegg da spørre autorisasjon om hvilke tilganger som er satt opp ifm broker-tjenesten.

**Comment by ToreMasoy** [comment]
Behov Helfo:
Tilrettelegge brukervennlige løsninger (GUI) for å sende og motta store filer 
•	Det skal være enkelt å laste opp og ned filer. Brukeren skal få gode instruksjoner og tilbakemeldinger underveis, inkludert en indikator som viser fremdrift på opp- og ned lasting.
•	Altinn formidling håndtere store filer, store filer kan ikke påvirker brukeropplevelsen.
•	Brukeren må få feilmeldinger dersom det oppstår problemer underveis i prosessen.
•	Det bør være mulig for mottaker å kun vise filen i en sikkert og enkelt tilgjengelig visningsmodus, uten å måtte laste den ned (Mottaker velger selv mellom nedlasting eller visning). - VIL VI IKKE BARE HA EN LENKE SOM VISES?
•	Avsender/mottaker må kunne få noe form for nedlastingsbekreftelse eller logg som informerer om dette. - AKTIVITETSLOGG
•	Det vil være nødvendig å kunne sende noe til enkelt person(er) i en virksomhet (Altså ikke til personens personlige innboks, men til virksomheten). Vi vet dette kan være utfordrende, men håper på en løsning. - KUN SENDE TIL ORGNR. SOM KAN DELEGERING PÅ TJENESTE ELLER INSTANS
•	Vi trenger å kunne laste opp større filmengder (opp til 2-5 gb totalt per sending) - 2GB INKL VIRUSSKANNING
•	Virus sjekk på utgående og innkommende filer. - BARE OPP TIL 2GB
•	Det må være sikker opplasting og nedlasting av filer. 
•	Vi trenger varighet på hvor lenge en sending er lagret hos mottaker etter den er åpnet/lastet ned. For eksempel 30 dager. - FAST GRENSE FOR ABSOLUTT ALLE FORMIDLINGSTJENESTENE??????
•	Egen tilgang for dem som skal bruke denne tjenesten på vår side - DELEGERING

**Comment by patattila** [comment]
Bruk bittorrent til dette. Kraken som uber bruker til å distribuere konteinere er basert på bittorrent. https://github.com/uber/kraken
