### ISSUE TITLE
Velge mottakskanal for forsendelser og varsler

### ISSUE THREAD

**Issue by erikhag1** [Altinn/altinn-broker#89]
## Users view

Title: **Velge mottakskanal for forsendelser og varsler**
User role(s): Mottaker
Users value statement(s): 
Denne personlige tilpasningen sørger for at jeg kan motta viktig kommunikasjon på den måten som passer best for meg, noe som øker sannsynligheten for at jeg er oppdatert og reagerer i tide. Dette bidrar til en bedre, mer strømlinjeformet kommunikasjon og en styrket tillit til avsenderen.

#### High level features (capabilities):
 * Støtte for valg av mottakskanal for forsendelser og varsler
#### Additional information
TBD

```[tasklist]
### Features
- [ ] Støtte for valg av mottakskanal per mottaker per formidlingstjeenste
- [ ] https://github.com/Altinn/altinn-broker/issues/136
- [ ] GUI for selvbetjent oppsett
- [ ] Valg mellom ulike meldingsløsninger?
```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 30_
_Stage: Operation_
_ArchiConceptID: id-b21304770c554a349df6afdf90cdc2c5_
_GithubIssueID: I_kwDOIwEQMM5vYMyU_

**Comment by erikhag1** [comment]
* For varsling; bygger på KoFiVi (virksomheter) ref. Core-teamet og KRR (personer) 
* Avklaringer mot varsling, autorisasjon osv.
* Avklaringer samspilll eFormidling/DPO osv.

**Comment by RagnarFatland-Avanade** [comment]
Avventer reelt behov.

**Comment by leogasnier** [comment]
Duplikat og usikkert behov
