### ISSUE TITLE
Lag "Skriftlig dokumentasjon av arkitekturskissen" slik at Juridisk vurdering kan ferdigstilles

### ISSUE THREAD

**Issue by ToreMasoy** [Altinn/altinn-broker#91]
```[tasklist]
### Tasks
- [x] Skjelett for innhold på docs.altinn.studio/broker
- [x] Bruksanvisning for dokumentasjon for team-medlemmene
- [ ] Minimum av detaljerte beskrivelser for overordnede arkitekturskisser
- [ ] Overordnet beskrivelse av trusler og informasjonssikkerhet
```

**Comment by leogasnier** [comment]
kan lukkes @erikhag1 ?
