### ISSUE TITLE
template test 1

### ISSUE THREAD

**Issue by erikhag1** [Altinn/altinn-broker#99]
## Users view

Title: **Velge mottakskanal for forsendelser og varsler**
User role(s): Mottaker
Users value statement(s): 
TBD

#### High level features (capabilities):
 * Støtte for valg av mottakskanal for forsendelser og varsler
#### Additional information
TBD

```[tasklist]
### Features 
- [ ] Støtte for valg av mottakskanal per forsendelse
- [ ] Støtte for kanaler SMS, e-post, events, API, ..
- [ ] GUI for selvbetjent oppsett
- [ ] Valg mellom ulike meldingsløsninger?
```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 30_
_Stage: Operation_
_ArchiConceptID: id-b21304770c554a349df6afdf90cdc2c5_
_GithubIssueID: I_kwDOIwEQMM5vYMyU_
